addSbtPlugin("io.get-coursier" % "sbt-coursier" % "2.0.0-RC3-3")
addSbtPlugin("ch.epfl.scala" % "sbt-release-early" % "2.1.1")
addSbtPlugin("ch.epfl.scala" % "sbt-pom-reader" % "2.1.0")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "2.1.0")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt" % "1.15")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.9.3")
